kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: aviatickets-pv-claim
  namespace: aviatickets
  labels:
    app: aviatickets-db
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi