apiVersion: v1
kind: ConfigMap
metadata:
  name: pgadmin-config
data:
  servers.json: |
    {
        "Servers": {
          "1": {
            "Name": "Aviatickets DB",
            "Group": "Servers",
            "Port": 5432,
            "Username": "postgres",
            "Host": "aviatickets-pgpool-service",
            "SSLMode": "prefer",
            "MaintenanceDB": "postgres"
          }
        }
    }